import { useEffect, useState } from "react";
import { Edit2, ToggleLeft, ToggleRight } from "lucide-react";
import AlertMessage from "../../components/AlertMessage";
import DataTable from "../../components/DataTable";
import FormField from "../../components/FormField";
import { categoryTypeLabels, changeCategoryStatus, createCategory, getCategories, updateCategory } from "../../services/settingsService";
import { getErrorMessage } from "../../utils/errors";

const empty={type:"EXPENSE",name:"",description:""};
export default function CategorySettings(){const[rows,setRows]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[filter,setFilter]=useState(""),[error,setError]=useState("");const load=(type=filter)=>getCategories(type).then(setRows).catch(err=>setError(getErrorMessage(err,"No fue posible cargar categorias")));useEffect(()=>{load("");},[]);const submit=async(e)=>{e.preventDefault();setError("");if(!form.name.trim())return setError("El nombre es obligatorio");try{editing?await updateCategory(editing,form):await createCategory(form);setForm(empty);setEditing(null);load();}catch(err){setError(getErrorMessage(err,"No fue posible guardar categoria"));}};const columns=[{key:"type",header:"Tipo",render:r=>categoryTypeLabels[r.type]},{key:"name",header:"Nombre",className:"font-medium"},{key:"description",header:"Descripcion"},{key:"isActive",header:"Estado",render:r=>r.isActive?"Activa":"Inactiva"},{key:"actions",header:"Acciones",align:"right",render:r=><div className="flex justify-end gap-2"><button onClick={()=>{setEditing(r.id);setForm({type:r.type,name:r.name,description:r.description||""});}} className="rounded-lg border p-2"><Edit2 size={16}/></button><button onClick={()=>changeCategoryStatus(r.id,!r.isActive).then(()=>load())} className="rounded-lg border p-2">{r.isActive?<ToggleRight size={16}/>:<ToggleLeft size={16}/>}</button></div>}];return <div className="space-y-6"><div><p className="text-sm font-semibold uppercase tracking-wide text-accent">Configuracion</p><h1 className="text-3xl font-semibold">Categorias</h1></div><AlertMessage>{error}</AlertMessage><section className="grid gap-6 xl:grid-cols-[360px_1fr]"><form onSubmit={submit} className="rounded-lg border bg-white p-5 shadow-soft"><h2 className="mb-4 font-semibold">{editing?"Editar":"Crear"} categoria</h2><FormField label="Tipo" as="select" value={form.type} onChange={v=>setForm({...form,type:v})}>{Object.entries(categoryTypeLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</FormField><FormField label="Nombre" value={form.name} onChange={v=>setForm({...form,name:v})}/><FormField label="Descripcion" value={form.description} onChange={v=>setForm({...form,description:v})}/><button className="rounded-lg bg-accent px-4 py-2 font-semibold text-white">Guardar</button></form><div className="space-y-4"><div className="rounded-lg border bg-white p-4 shadow-soft"><FormField label="Filtrar tipo" as="select" value={filter} onChange={v=>{setFilter(v);load(v);}}><option value="">Todos</option>{Object.entries(categoryTypeLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</FormField></div><DataTable columns={columns} rows={rows} minWidth="820px" emptyTitle="Sin categorias"/></div></section></div>;}
