import { useEffect, useState } from "react";
import { Edit2, ToggleLeft, ToggleRight } from "lucide-react";
import AlertMessage from "../../components/AlertMessage";
import DataTable from "../../components/DataTable";
import FormField from "../../components/FormField";
import { changeNumberingStatus, createNumbering, documentTypeLabels, getNumbering, updateNumbering } from "../../services/settingsService";
import { getErrorMessage } from "../../utils/errors";

const empty={documentType:"INVOICE",prefix:"FAC",nextNumber:1,padding:6,isActive:true};
export default function NumberingSettings(){const[rows,setRows]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[error,setError]=useState("");const load=()=>getNumbering().then(setRows).catch(err=>setError(getErrorMessage(err,"No fue posible cargar numeracion")));useEffect(()=>{load();},[]);const preview=`${form.prefix||"DOC"}-${String(form.nextNumber||1).padStart(Number(form.padding||6),"0")}`;const submit=async(e)=>{e.preventDefault();setError("");if(!form.prefix.trim())return setError("El prefijo es obligatorio");if(Number(form.nextNumber)<1)return setError("El siguiente numero debe ser mayor a cero");if(Number(form.padding)<1)return setError("El padding debe ser mayor a cero");try{editing?await updateNumbering(editing,form):await createNumbering(form);setForm(empty);setEditing(null);load();}catch(err){setError(getErrorMessage(err,"No fue posible guardar numeracion"));}};const columns=[{key:"documentType",header:"Tipo",render:r=>documentTypeLabels[r.documentType]},{key:"prefix",header:"Prefijo"},{key:"nextNumber",header:"Siguiente"},{key:"padding",header:"Padding"},{key:"isActive",header:"Estado",render:r=>r.isActive?"Activa":"Inactiva"},{key:"actions",header:"Acciones",align:"right",render:r=><div className="flex justify-end gap-2"><button onClick={()=>{setEditing(r.id);setForm({...r});}} className="rounded-lg border p-2"><Edit2 size={16}/></button><button onClick={()=>changeNumberingStatus(r.id,!r.isActive).then(load)} className="rounded-lg border p-2">{r.isActive?<ToggleRight size={16}/>:<ToggleLeft size={16}/>}</button></div>}];return <div className="space-y-6"><div><p className="text-sm font-semibold uppercase tracking-wide text-accent">Configuracion</p><h1 className="text-3xl font-semibold">Numeracion</h1></div><AlertMessage>{error}</AlertMessage><section className="grid gap-6 xl:grid-cols-[360px_1fr]"><form onSubmit={submit} className="rounded-lg border bg-white p-5 shadow-soft"><h2 className="mb-4 font-semibold">{editing?"Editar":"Crear"} numeracion</h2><FormField label="Tipo" as="select" value={form.documentType} onChange={v=>setForm({...form,documentType:v})}>{Object.entries(documentTypeLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</FormField><FormField label="Prefijo" value={form.prefix} onChange={v=>setForm({...form,prefix:v})}/><FormField label="Siguiente numero" type="number" min={1} value={form.nextNumber} onChange={v=>setForm({...form,nextNumber:v})}/><FormField label="Padding" type="number" min={1} value={form.padding} onChange={v=>setForm({...form,padding:v})}/><p className="mb-4 rounded-lg bg-slate-50 p-3 text-sm">Vista previa: <strong>{preview}</strong></p><button className="rounded-lg bg-accent px-4 py-2 font-semibold text-white">Guardar</button></form><DataTable columns={columns} rows={rows} minWidth="820px" emptyTitle="Sin numeraciones"/></section></div>;}
